openapi: 3.0.0
info:
  title: SGLCN-X20 Minting API
  version: 1.0.0
  description: |
    Public API for minting NFTs with SeagullCoin (SGLCN-X20) only. 
    - Mint NFTs by paying 0.5 SeagullCoin.
    - No XRP purchases allowed.
    - Only SeagullCoin can be used for offers, sales, or mints.
    - Supports CORS for marketplaces like bidds.com and xrp.cafe.
servers:
  - url: https://sglcn-x20-api.glitch.me
    description: Main API server

paths:
  /pay:
    post:
      summary: "Initiate payment of 0.5 SeagullCoin to mint an NFT"
      operationId: initiatePayment
      tags:
        - Payment
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                walletAddress:
                  type: string
                  description: The wallet address initiating the payment
                amount:
                  type: number
                  format: float
                  description: Amount of SeagullCoin to be paid (0.5 SGLCN required)
                  example: 0.5
      responses:
        '200':
          description: "Payment initiated successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  paymentId:
                    type: string
                    description: "Unique payment identifier"
        '400':
          description: "Invalid request or insufficient payment"
        '500':
          description: "Internal server error"

  /mint:
    post:
      summary: "Mint an NFT after confirming payment"
      operationId: mintNFT
      tags:
        - Minting
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                nft_name:
                  type: string
                  description: Name of the NFT
                nft_description:
                  type: string
                  description: Description of the NFT
                nft_file:
                  type: string
                  format: binary
                  description: The file to be uploaded for the NFT (image/video)
                domain:
                  type: string
                  description: Optional domain for the NFT
                properties:
                  type: string
                  description: JSON string of additional properties (optional)
      responses:
        '200':
          description: "NFT minted successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  mintResult:
                    type: object
                    properties:
                      nftId:
                        type: string
                        description: "Unique identifier for the minted NFT"
        '400':
          description: "Invalid request, missing required parameters or invalid file format"
        '402':
          description: "Payment verification failed"
        '500':
          description: "Internal server error"

  /user:
    get:
      summary: "Get NFTs owned by a wallet"
      operationId: getUserNFTs
      tags:
        - User
      parameters:
        - in: query
          name: walletAddress
          required: true
          schema:
            type: string
          description: The wallet address to query for NFTs
      responses:
        '200':
          description: "NFTs retrieved successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  nfts:
                    type: array
                    items:
                      type: object
                      properties:
                        nftId:
                          type: string
                          description: "Unique identifier for the NFT"
                        name:
                          type: string
                          description: "Name of the NFT"
                        description:
                          type: string
                          description: "Description of the NFT"
                        metadata:
                          type: object
                          additionalProperties: true
                          description: "Metadata for the NFT"
        '400':
          description: "Invalid request or wallet address"
        '500':
          description: "Internal server error"
  
  /nfts:
    get:
      summary: "List all NFTs available on the platform"
      operationId: listNFTs
      tags:
        - NFT
      parameters:
        - in: query
          name: page
          required: false
          schema:
            type: integer
            default: 1
          description: "Page number for pagination"
        - in: query
          name: limit
          required: false
          schema:
            type: integer
            default: 10
          description: "Number of NFTs to return per page"
      responses:
        '200':
          description: "List of NFTs"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  nfts:
                    type: array
                    items:
                      type: object
                      properties:
                        nftId:
                          type: string
                          description: "Unique identifier for the NFT"
                        name:
                          type: string
                          description: "Name of the NFT"
                        description:
                          type: string
                          description: "Description of the NFT"
        '500':
          description: "Internal server error"

  /nft/{nftId}:
    get:
      summary: "Get details of a specific NFT"
      operationId: getNFTDetails
      tags:
        - NFT
      parameters:
        - in: path
          name: nftId
          required: true
          schema:
            type: string
          description: "The ID of the NFT"
      responses:
        '200':
          description: "NFT details retrieved successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  nft:
                    type: object
                    properties:
                      nftId:
                        type: string
                        description: "Unique identifier for the NFT"
                      name:
                        type: string
                        description: "Name of the NFT"
                      description:
                        type: string
                        description: "Description of the NFT"
                      metadata:
                        type: object
                        additionalProperties: true
                        description: "Metadata for the NFT"
        '400':
          description: "Invalid NFT ID"
        '500':
          description: "Internal server error"

  /make-offer:
    post:
      summary: "Make an offer to buy an NFT"
      operationId: makeOffer
      tags:
        - Offers
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nftId:
                  type: string
                  description: "The ID of the NFT being offered on"
                offerAmount:
                  type: number
                  format: float
                  description: "Amount of SeagullCoin being offered"
      responses:
        '200':
          description: "Offer made successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  offerId:
                    type: string
                    description: "Unique identifier for the offer"
        '400':
          description: "Invalid offer details"
        '500':
          description: "Internal server error"

  /accept-offer:
    post:
      summary: "Accept an offer for an NFT"
      operationId: acceptOffer
      tags:
        - Offers
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                offerId:
                  type: string
                  description: "Offer ID to accept"
                nftId:
                  type: string
                  description: "NFT ID being sold"
      responses:
        '200':
          description: "Offer accepted and NFT transferred"
        '400':
          description: "Invalid offer ID or NFT ID"
        '500':
          description: "Internal server error"

  /transfer-nft:
    post:
      summary: "Transfer ownership of an NFT"
      operationId: transferNFT
      tags:
        - NFT Transfer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nftId:
                  type: string
                  description: "The NFT ID being transferred"
                toAddress:
                  type: string
                  description: "The wallet address receiving the NFT"
      responses:
        '200':
          description: "NFT successfully transferred"
        '400':
          description: "Invalid request or transfer details"
        '500':
          description: "Internal server error"
