openapi: 3.0.0
info:
  title: SGLCN-X20 Minting API
  version: "1.0.0"
  description: |
    API for minting and buying NFTs using SeagullCoin (SGLCN-X20).
    - Mint NFTs (with media upload)
    - Buy NFTs
    - Sell NFTs
    - View NFTs for sale
    - XUMM OAuth2 login
    - Place offers and bids on NFTs
    - Auction system for NFTs
    - Manage NFT collections
    - View platform metrics
servers:
  - url: https://sglcn-x20-api.glitch.me
    description: Production server
paths:
  /:
    get:
      summary: Welcome
      description: Welcome message and API information.
      responses:
        '200':
          description: API welcome message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Welcome to the SGLCN-X20 Minting API"
  /api/login:
    get:
      summary: XUMM OAuth2 Login
      description: Redirects user to XUMM OAuth2 login page.
      responses:
        '302':
          description: Redirect to XUMM login page
  /mint:
    post:
      summary: Mint a new NFT
      description: Mint a new NFT after verifying SeagullCoin payment.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                nft_name:
                  type: string
                  description: Name of the NFT
                nft_description:
                  type: string
                  description: Description of the NFT
                domain:
                  type: string
                  description: Domain linked to the NFT
                properties:
                  type: string
                  description: JSON stringified additional properties
                nft_file:
                  type: string
                  format: binary
                  description: Image or video file for the NFT
      responses:
        '200':
          description: Successfully minted NFT
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  mintResult:
                    type: object
        '400':
          description: Bad Request (e.g., missing fields, payment not found)
        '500':
          description: Internal Server Error
      security:
        - XUMM_OAuth2: []
  /buy-nft:
    post:
      summary: Buy an NFT
      description: Purchase an NFT after verifying SeagullCoin payment.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nftId:
                  type: string
                  description: ID of the NFT to purchase
                price:
                  type: string
                  description: Price to pay in SeagullCoin
      responses:
        '200':
          description: Successfully purchased NFT
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  purchaseResult:
                    type: object
        '400':
          description: Bad Request (e.g., missing fields, payment not verified)
        '500':
          description: Internal Server Error
      security:
        - XUMM_OAuth2: []
  /sell-nft:
    post:
      summary: Sell an NFT
      description: List an NFT for sale after verifying SeagullCoin payment.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nftId:
                  type: string
                  description: ID of the NFT to sell
                price:
                  type: string
                  description: Price to sell the NFT in SeagullCoin
      responses:
        '200':
          description: Successfully listed NFT for sale
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  saleResult:
                    type: object
        '400':
          description: Bad Request (e.g., missing fields, invalid price)
        '402':
          description: Payment Required (SeagullCoin payment not verified)
        '500':
          description: Internal Server Error
      security:
        - XUMM_OAuth2: []
  /place-offer:
    post:
      summary: Place an offer on an NFT
      description: Place an offer to buy an NFT at a specific price in SeagullCoin.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nftId:
                  type: string
                  description: ID of the NFT to place the offer on
                offerPrice:
                  type: string
                  description: Offer price in SeagullCoin
      responses:
        '200':
          description: Successfully placed offer
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  offerResult:
                    type: object
        '400':
          description: Bad Request (e.g., missing fields, invalid price)
        '500':
          description: Internal Server Error
      security:
        - XUMM_OAuth2: []
  /place-bid:
    post:
      summary: Place a bid on an NFT
      description: Place a bid to purchase an NFT at a higher price in SeagullCoin.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nftId:
                  type: string
                  description: ID of the NFT to place a bid on
                bidPrice:
                  type: string
                  description: Bid price in SeagullCoin
      responses:
        '200':
          description: Successfully placed bid
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  bidResult:
                    type: object
        '400':
          description: Bad Request (e.g., missing fields, invalid price)
        '500':
          description: Internal Server Error
      security:
        - XUMM_OAuth2: []
  /auction/start:
    post:
      summary: Start an NFT auction
      description: Starts an auction for an NFT with a set reserve price and auction duration.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nftId:
                  type: string
                  description: ID of the NFT to start the auction for
                reservePrice:
                  type: string
                  description: Reserve price in SeagullCoin
                duration:
                  type: integer
                  description: Auction duration in seconds
      responses:
        '200':
          description: Successfully started auction
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  auctionResult:
                    type: object
        '400':
          description: Bad Request (e.g., missing fields, invalid price)
        '500':
          description: Internal Server Error
      security:
        - XUMM_OAuth2: []
  /auction/close:
    post:
      summary: Close an NFT auction
      description: Closes an NFT auction and determines the winner.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nftId:
                  type: string
                  description: ID of the NFT auction to close
      responses:
        '200':
          description: Successfully closed auction
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  closeResult:
                    type: object
        '400':
          description: Bad Request (e.g., auction already closed)
        '500':
          description: Internal Server Error
      security:
        - XUMM_OAuth2: []
  /user/profile:
    get:
      summary: Get user profile
      description: Retrieves the user's profile, including owned NFTs and wallet balance.
      responses:
        '200':
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  profile:
                    type: object
                    properties:
                      walletAddress:
                        type: string
                        description: User's wallet address
                      nftsOwned:
                        type: array
                        items:
                          type: string
                        description: List of NFTs owned by the user
                      balance:
                        type: string
                        description: SeagullCoin balance
        '500':
          description: Internal Server Error
      security:
        - XUMM_OAuth2: []
  /user/transactions:
    get:
      summary: Get user transaction history
      description: Retrieves the user's NFT transaction history (minted, bought, sold).
      responses:
        '200':
          description: Transaction history retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  transactions:
                    type: array
                    items:
                      type: object
                      properties:
                        transactionId:
                          type: string
                        nftId:
                          type: string
                        transactionType:
                          type: string
                        price:
                          type: string
                        timestamp:
                          type: string
        '500':
          description: Internal Server Error
      security:
        - XUMM_OAuth2: []
  /metrics:
    get:
      summary: Retrieve platform metrics
      description: Fetches the current statistics like total NFTs minted, SeagullCoin payments processed, etc.
      responses:
        '200':
          description: Metrics successfully retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalMinted:
                    type: integer
                    description: Total NFTs minted
                  totalPayments:
                    type: integer
                    description: Total SeagullCoin payments processed
        '500':
          description: Internal Server Error
  /collections:
    get:
      summary: Retrieve all collections
      description: Fetches a list of all NFT collections available on the platform.
      responses:
        '200':
          description: Collections retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    collectionName:
                      type: string
                      description: The name of the collection
                    collectionLogo:
                      type: string
                      description: URL to the collection's logo image
                    collectionDescription:
                      type: string
                      description: A brief description of the collection
    post:
      summary: Create a new NFT collection
      description: Allows users to create a new collection by specifying a name, logo, and description.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                collectionName:
                  type: string
                  description: Name of the new collection
                collectionLogo:
                  type: string
                  description: URL of the logo image for the collection
                collectionDescription:
                  type: string
                  description: Description of the collection
      responses:
        '200':
          description: Collection created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  collectionResult:
                    type: object
        '400':
          description: Bad Request (e.g., missing fields)
        '500':
          description: Internal Server Error
      security:
        - XUMM_OAuth2: []
