openapi: 3.0.0
info:
  title: SGLCN-X20 Minting API
  version: 1.0.0
  description: |
    Public API for minting NFTs with SeagullCoin (SGLCN-X20) only.
    - Mint NFTs by paying 0.5 SeagullCoin.
    - No XRP purchases allowed.
    - Only SeagullCoin (X20 token) allowed for offers, mints, and sales.
    - Supports CORS for marketplaces like bidds.com and xrp.cafe.
  contact:
    name: Bored Seagull Club
    email: boredseagulls@gmail.com
    url: https://linktr.ee/boredseagullclub

servers:
  - url: 'https://sglcn-x20-api.glitch.me'
    description: Main API server

paths:
  /login:
    post:
      summary: Initiate XUMM login session
      operationId: loginUser
      tags:
        - Authentication
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                userToken:
                  type: string
                  description: Optional existing XUMM user token
      responses:
        '200':
          description: Login payload generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  loginPayload:
                    type: object
                    description: XUMM login payload details
                  qrUrl:
                    type: string
                    description: QR URL for user to scan
                  websocketUrl:
                    type: string
                    description: WebSocket URL for real-time updates
        '500':
          description: Error initiating login

  /pay:
    post:
      summary: Initiate payment of 0.5 SeagullCoin
      operationId: initiatePayment
      tags:
        - Payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - walletAddress
              properties:
                walletAddress:
                  type: string
                  description: Wallet address initiating payment
      responses:
        '200':
          description: Payment initiated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  paymentId:
                    type: string
        '400':
          description: Invalid request (missing or invalid wallet address)
        '500':
          description: Server error during payment initiation

  /mint:
    post:
      summary: Mint a new NFT after payment
      operationId: mintNFT
      tags:
        - NFT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - walletAddress
                - metadata
              properties:
                walletAddress:
                  type: string
                  description: Wallet address minting the NFT
                metadata:
                  type: object
                  description: NFT metadata (e.g., name, description, image link, etc.)
      responses:
        '200':
          description: NFT minted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  nftokenId:
                    type: string
        '400':
          description: Invalid mint request (missing metadata, etc.)
        '500':
          description: Server error during minting

  /user:
    get:
      summary: Get connected user wallet info
      operationId: getUser
      tags:
        - User
      parameters:
        - name: token
          in: query
          description: XUMM user token
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User wallet info returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  walletAddress:
                    type: string
                  balance:
                    type: number
                    format: float
        '400':
          description: Invalid token or missing token
        '500':
          description: Server error fetching user wallet info

  /nfts:
    get:
      summary: List all minted NFTs
      operationId: listNFTs
      tags:
        - NFT
      responses:
        '200':
          description: List of all NFTs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    metadata:
                      type: object
                      description: NFT metadata (e.g., name, description)
        '500':
          description: Server error listing NFTs

  /nft/{nftId}:
    get:
      summary: Get NFT details
      operationId: getNFT
      tags:
        - NFT
      parameters:
        - name: nftId
          in: path
          required: true
          description: NFTokenID of the NFT to fetch
          schema:
            type: string
      responses:
        '200':
          description: NFT details returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  metadata:
                    type: object
        '404':
          description: NFT not found
        '500':
          description: Server error fetching NFT

  /buy-nft:
    post:
      summary: Buy an NFT by sending a SeagullCoin transaction
      operationId: buyNFT
      tags:
        - NFT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - nftId
                - price
                - currency
              properties:
                nftId:
                  type: string
                  description: NFT ID to purchase
                price:
                  type: number
                  format: float
                  description: Price of the NFT in SeagullCoin
                currency:
                  type: string
                  enum: [SeagullCoin]
                  description: Currency for purchase (must be SeagullCoin)
      responses:
        '200':
          description: NFT successfully purchased
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  txHash:
                    type: string
        '400':
          description: Invalid parameters or wrong currency
        '402':
          description: Insufficient SeagullCoin
        '500':
          description: Server error during purchase

  /sell-nft:
    post:
      summary: Sell an NFT on the marketplace
      operationId: sellNFT
      tags:
        - NFT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - nftId
                - price
                - currency
              properties:
                nftId:
                  type: string
                  description: NFT ID to list for sale
                price:
                  type: number
                  format: float
                  description: Price to list NFT for in SeagullCoin
                currency:
                  type: string
                  enum: [SeagullCoin]
                  description: Currency in which the NFT is listed (must be SeagullCoin)
      responses:
        '200':
          description: NFT successfully listed for sale
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '400':
          description: Invalid parameters or wrong currency
        '500':
          description: Server error during listing

  /unlist-nft:
    post:
      summary: Unlist an NFT from sale
      operationId: unlistNFT
      tags:
        - NFT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - nftId
              properties:
                nftId:
                  type: string
                  description: The NFT ID to unlist
      responses:
        '200':
          description: NFT successfully unlisted
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '400':
          description: User not logged in or unauthorized action
        '500':
          description: Server error during unlisting

  /check-ownership/{nftId}:
    get:
      summary: Check NFT ownership
      operationId: checkOwnership
      tags:
        - NFT
      parameters:
        - name: nftId
          in: path
          required: true
          description: The NFT ID to check ownership for
          schema:
            type: string
      responses:
        '200':
          description: Ownership info returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  owner:
                    type: string
                    description: Wallet address of the NFT owner
        '404':
          description: Ownership not found
        '500':
          description: Server error during ownership check
