openapi: 3.0.0
info:
  title: SGLCN-X20 Minting API
  description: API for minting and interacting with SeagullCoin-based NFTs.
  version: 1.0.0
  contact:
    name: Bored Seagull Club
    email: boredseagulls@gmail.com
    url: https://linktr.ee/boredseagullclub

servers:
  - url: 'https://sglcn-x20-api.glitch.me/api'

paths:
  /login/start:
    get:
      summary: Start XUMM OAuth2 login
      description: Redirects the user to the XUMM OAuth2 login page.
      responses:
        '302':
          description: Redirects to XUMM login page

  /login/check:
    get:
      summary: Check XUMM OAuth2 login status
      description: Checks if a user has successfully logged in via XUMM.
      parameters:
        - in: query
          name: payloadUuid
          required: true
          schema:
            type: string
          description: The XUMM payload UUID to check login status
      responses:
        '200':
          description: Login status (signed or not)
          content:
            application/json:
              schema:
                type: object
                properties:
                  signed:
                    type: boolean
                  walletAddress:
                    type: string
                    nullable: true
        '400':
          description: Missing or invalid payloadUuid
        '500':
          description: Server error checking login status

  /mint:
    post:
      summary: Mint a new NFT
      description: Allows users to mint a new NFT with a SeagullCoin payment.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                nft_file:
                  type: string
                  format: binary
                  description: The file representing the NFT media.
                nft_name:
                  type: string
                  description: The name of the NFT.
                nft_description:
                  type: string
                  description: The description of the NFT.
                domain:
                  type: string
                  description: (Optional) Domain name associated with the NFT.
                properties:
                  type: string
                  description: (Optional) Properties related to the NFT (in JSON format).
      responses:
        '200':
          description: NFT successfully minted
        '400':
          description: Missing required fields
        '402':
          description: Payment required (0.5 SeagullCoin)
        '500':
          description: Internal server error

  /check-ownership/{nftId}:
    get:
      summary: Check NFT ownership
      description: Checks if a user owns a specific NFT.
      parameters:
        - in: path
          name: nftId
          required: true
          schema:
            type: string
          description: The NFT ID to check ownership for
      responses:
        '200':
          description: Ownership information
        '400':
          description: Missing NFT ID
        '404':
          description: Ownership not found
        '500':
          description: Internal server error

  /buy-nft:
    post:
      summary: Buy an NFT
      description: Allows users to buy an NFT by sending a SeagullCoin transaction.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nftId:
                  type: string
                  description: The NFT ID to buy
                price:
                  type: string
                  description: The price in SeagullCoin to buy the NFT
      responses:
        '200':
          description: NFT purchase successful
        '400':
          description: Missing required fields
        '402':
          description: Insufficient SeagullCoin payment
        '500':
          description: Internal server error

  /accept-offer:
    post:
      summary: Accept an NFT offer
      description: Accept an offer to buy or sell an NFT.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                walletAddress:
                  type: string
                  description: The wallet address accepting the offer
                nftokenId:
                  type: string
                  description: The NFT ID of the item being transferred
                offerTxid:
                  type: string
                  description: The transaction ID of the offer to be accepted
      responses:
        '200':
          description: Offer accepted successfully, NFT transferred
        '400':
          description: Missing required fields
        '500':
          description: Internal server error

components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://oauth2.xumm.app/auth
          tokenUrl: https://xumm.app/api/v1/oauth/token
          scopes:
            identity: "Access to user identity"
            payload: "Create and send payloads"

security:
  - oauth2: [identity, payload]
