openapi: 3.0.0
info:
  title: SGLCN-X20 Minting API
  description: API for minting and interacting with SeagullCoin-based NFTs.
  version: 1.0.0
  contact:
    name: Your Name
    email: your-email@example.com
    url: https://yourwebsite.com

servers:
  - url: 'http://localhost:3000/api'

paths:
  /login:
    get:
      summary: Login via XUMM OAuth2
      description: Redirects to the XUMM OAuth2 login page.
      responses:
        '302':
          description: Redirects to XUMM login
          
  /xumm/callback:
    get:
      summary: XUMM OAuth2 Callback
      description: Handles the OAuth2 callback from XUMM.
      parameters:
        - in: query
          name: code
          required: true
          schema:
            type: string
          description: The authorization code from XUMM
      responses:
        '200':
          description: Successfully logged in
        '400':
          description: Missing authorization code
        '500':
          description: Failed to process XUMM callback

  /mint:
    post:
      summary: Mint a new NFT
      description: Allows users to mint a new NFT with a SeagullCoin payment.
      parameters:
        - in: formData
          name: nft_file
          required: true
          description: The file representing the NFT media.
          type: file
        - in: formData
          name: nft_name
          required: true
          description: The name of the NFT.
          type: string
        - in: formData
          name: nft_description
          required: true
          description: The description of the NFT.
          type: string
        - in: formData
          name: domain
          required: false
          description: Domain name associated with the NFT.
          type: string
        - in: formData
          name: properties
          required: false
          description: Properties related to the NFT (in JSON format).
          type: string
      responses:
        '200':
          description: NFT successfully minted
        '400':
          description: Missing required fields
        '402':
          description: Payment required (0.5 SeagullCoin)
        '500':
          description: Internal server error

  /check-ownership/{nftId}:
    get:
      summary: Check NFT ownership
      description: Checks if a user owns a specific NFT.
      parameters:
        - in: path
          name: nftId
          required: true
          description: The NFT ID to check ownership for.
          schema:
            type: string
      responses:
        '200':
          description: Ownership information
        '400':
          description: Missing NFT ID
        '404':
          description: Ownership not found
        '500':
          description: Internal server error

  /buy-nft:
    post:
      summary: Buy an NFT
      description: Allows users to buy an NFT by sending a SeagullCoin transaction.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nftId:
                  type: string
                  description: The NFT ID to buy
                price:
                  type: string
                  description: The price in SeagullCoin to buy the NFT
      responses:
        '200':
          description: NFT purchase successful
        '400':
          description: Missing required fields
        '402':
          description: Insufficient SeagullCoin payment
        '500':
          description: Internal server error

  /accept-offer:
    post:
      summary: Accept an NFT offer
      description: Accept an offer to buy or sell an NFT.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                walletAddress:
                  type: string
                  description: The wallet address accepting the offer.
                nftokenId:
                  type: string
                  description: The NFT ID of the item being transferred.
                offerTxid:
                  type: string
                  description: The transaction ID of the offer to be accepted.
      responses:
        '200':
          description: Offer accepted successfully, NFT transferred.
        '400':
          description: Missing required fields
        '500':
          description: Internal server error

components:
  securitySchemes:
    oauth2:
      type: oauth2
      authorizationUrl: https://oauth2.xumm.app/auth
      tokenUrl: https://xumm.app/api/v1/oauth/token
      scopes:
        identity: "Access to user identity"
        payload: "Create and send payloads"
  security:
    - oauth2: [identity, payload]
