openapi: 3.0.0
info:
  title: SGLCN-X20 Minting API
  version: 1.0.0
  description: |
    Public API for minting NFTs with SeagullCoin (SGLCN-X20) only.
    - Mint NFTs by paying 0.5 SeagullCoin.
    - No XRP purchases allowed.
    - Only SeagullCoin (X20 token) allowed for offers, mints, and sales.
    - Supports CORS for marketplaces like bidds.com and xrp.cafe.
  contact:
    name: Bored Seagull Club
    email: boredseagulls@gmail.com
    url: https://linktr.ee/boredseagullclub

servers:
  - url: 'https://sglcn-x20-api.glitch.me'
    description: Main API server

paths:
  /login:
    post:
      summary: Initiate XUMM login session
      operationId: loginUser
      tags:
        - Authentication
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                userToken:
                  type: string
                  description: Optional existing XUMM user token
      responses:
        '200':
          description: Login payload generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  loginPayload:
                    type: object
                    description: XUMM login payload details
                  qrUrl:
                    type: string
                    description: QR URL for user to scan
                  websocketUrl:
                    type: string
                    description: WebSocket URL for real-time updates
        '500':
          description: Error initiating login

  /pay:
    post:
      summary: Initiate payment of 0.5 SeagullCoin
      operationId: initiatePayment
      tags:
        - Payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - walletAddress
              properties:
                walletAddress:
                  type: string
                  description: Wallet address initiating payment
      responses:
        '200':
          description: Payment initiated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  paymentId:
                    type: string
        '400':
          description: Invalid request (missing or invalid wallet address)
        '500':
          description: Server error during payment initiation

  /validate-payment:
    post:
      summary: Validate the payment for NFT minting
      operationId: validatePayment
      tags:
        - Payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - paymentId
              properties:
                paymentId:
                  type: string
                  description: Payment ID for validation
      responses:
        '200':
          description: Payment successfully validated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  status:
                    type: string
                    description: Payment status (e.g., successful, pending)
        '400':
          description: Invalid payment ID or missing data
        '500':
          description: Server error during payment validation

  /mint:
    post:
      summary: Mint a new NFT after payment
      operationId: mintNFT
      tags:
        - NFT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - walletAddress
                - metadata
              properties:
                walletAddress:
                  type: string
                  description: Wallet address minting the NFT
                metadata:
                  type: object
                  description: NFT metadata (e.g., name, description, image link, etc.)
      responses:
        '200':
          description: NFT minted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  nftokenId:
                    type: string
        '400':
          description: Invalid mint request (missing metadata, etc.)
        '500':
          description: Server error during minting

  /collections:
    get:
      summary: List all NFT collections
      operationId: listCollections
      tags:
        - Collections
      responses:
        '200':
          description: List of all collections
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    collectionId:
                      type: string
                    name:
                      type: string
                    logo:
                      type: string
        '500':
          description: Server error listing collections

    post:
      summary: Create a new NFT collection
      operationId: createCollection
      tags:
        - Collections
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - logo
              properties:
                name:
                  type: string
                  description: Collection name
                logo:
                  type: string
                  description: URL or IPFS link to the collection logo
      responses:
        '201':
          description: Collection created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  collectionId:
                    type: string
        '400':
          description: Missing or invalid collection data
        '500':
          description: Server error during collection creation

  /nfts:
    get:
      summary: List all minted NFTs
      operationId: listNFTs
      tags:
        - NFT
      responses:
        '200':
          description: List of all NFTs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    metadata:
                      type: object
                      description: NFT metadata (e.g., name, description)
        '500':
          description: Server error listing NFTs

    post:
      summary: Create a new NFT
      operationId: createNFT
      tags:
        - NFT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - metadata
              properties:
                metadata:
                  type: object
                  description: NFT metadata (e.g., name, description, image link, etc.)
      responses:
        '201':
          description: NFT created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  nftokenId:
                    type: string
        '400':
          description: Invalid NFT creation request (missing metadata, etc.)
        '500':
          description: Server error during NFT creation

    patch:
      summary: Update NFT metadata
      operationId: updateNFT
      tags:
        - NFT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - nftId
                - metadata
              properties:
                nftId:
                  type: string
                  description: NFT ID to update
                metadata:
                  type: object
                  description: Updated metadata for the NFT
      responses:
        '200':
          description: NFT metadata updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        '400':
          description: Invalid NFT ID or metadata
        '500':
          description: Server error during NFT update

  /offers:
    get:
      summary: Get all offers on NFTs
      operationId: listOffers
      tags:
        - Offers
      responses:
        '200':
          description: List of all NFT offers
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    offerId:
                      type: string
                    nftId:
                      type: string
                    amount:
                      type: number
                      format: float
        '500':
          description: Server error listing offers

    post:
      summary: Create a new offer to buy an NFT
      operationId: createOffer
      tags:
        - Offers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - nftId
                - amount
              properties:
                nftId:
                  type: string
                  description: The NFT ID for the offer
                amount:
                  type: number
                  format: float
                  description: The offer amount in SeagullCoin
      responses:
        '201':
          description: Offer created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  offerId:
                    type: string
        '400':
          description: Invalid offer request
        '500':
          description: Server error creating offer

    delete:
      summary: Reject an NFT offer
      operationId: rejectOffer
      tags:
        - Offers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - offerId
              properties:
                offerId:
                  type: string
                  description: Offer ID to reject
      responses:
        '200':
          description: Offer successfully rejected
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        '400':
          description: Invalid offer ID
        '500':
          description: Server error rejecting offer

  /transactions:
    get:
      summary: Get all user transactions
      operationId: listTransactions
      tags:
        - Transactions
      parameters:
        - name: walletAddress
          in: query
          required: true
          description: Wallet address to retrieve transactions for
          schema:
            type: string
      responses:
        '200':
          description: List of all transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    transactionId:
                      type: string
                    amount:
                      type: number
                      format: float
                    type:
                      type: string
                      description: Transaction type (e.g., mint, buy, sell)
        '500':
          description: Server error listing transactions

  /accept-offer:
    post:
      summary: Accept an NFT offer
      operationId: acceptOffer
      tags:
        - Offers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - offerId
                - nftId
              properties:
                offerId:
                  type: string
                  description: Offer ID to accept
                nftId:
                  type: string
                  description: NFT ID to be sold
      responses:
        '200':
          description: Offer accepted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        '400':
          description: Invalid offer or NFT ID
        '500':
          description: Server error accepting offer
