openapi: 3.0.0
info:
  title: SGLCN-X20 Minting API
  version: 1.0.0
  description: Public API for minting, managing, and transacting NFTs using SeagullCoin on XRPL.
servers:
  - url: https://sglcn-x20-api.glitch.me
paths:
  /login:
    post:
      summary: Initiate XUMM login session
      tags: [Authentication]
      responses:
        '200':
          description: XUMM login QR and reference

  /pay:
    post:
      summary: Initiate payment of 0.5 SeagullCoin
      tags: [Payment]
      responses:
        '200':
          description: Payment payload generated

  /validate-payment:
    post:
      summary: Validate the payment for NFT minting
      tags: [Payment]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                wallet:
                  type: string
      responses:
        '200':
          description: Payment status

  /mint:
    post:
      summary: Mint a new NFT after payment
      tags: [NFT]
      responses:
        '200':
          description: NFT minted

  /burn:
    post:
      summary: Burn (delete) an existing NFT
      tags: [NFT]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nftId:
                  type: string
      responses:
        '200':
          description: NFT burned

  /nfts:
    get:
      summary: List all minted NFTs
      tags: [NFT]
      responses:
        '200':
          description: All NFTs

  /nfts/{id}:
    get:
      summary: Retrieve a specific NFT
      tags: [NFT]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: NFT details

  /collections:
    get:
      summary: List all NFT collections
      tags: [Collections]
      responses:
        '200':
          description: All collections

    post:
      summary: Create a new NFT collection
      tags: [Collections]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                icon:
                  type: string
                description:
                  type: string
      responses:
        '201':
          description: Collection created

  /collections/{collectionId}:
    get:
      summary: Get NFTs in a collection
      tags: [Collections]
      parameters:
        - in: path
          name: collectionId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: NFTs in collection

  /offers:
    post:
      summary: Create a new offer
      tags: [Offers]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nftId:
                  type: string
                amount:
                  type: string
                direction:
                  type: string
                  enum: [buy, sell]
                wallet:
                  type: string
      responses:
        '200':
          description: Offer created

  /offers/{offerId}:
    delete:
      summary: Reject/cancel offer
      tags: [Offers]
      parameters:
        - in: path
          name: offerId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Offer cancelled

  /accept-offer:
    post:
      summary: Accept an offer
      tags: [Offers]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                offerId:
                  type: string
      responses:
        '200':
          description: Offer accepted

  /offers/{nftId}:
    get:
      summary: Get all offers for an NFT
      tags: [Offers]
      parameters:
        - in: path
          name: nftId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of offers for NFT

  /buy:
    post:
      summary: Create a buy offer for an NFT
      tags: [Buy & Sell]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nftId:
                  type: string
                amount:
                  type: string
                buyerWallet:
                  type: string
      responses:
        '200':
          description: Buy offer created

  /sell:
    post:
      summary: List an NFT for sale
      tags: [Buy & Sell]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nftId:
                  type: string
                amount:
                  type: string
                sellerWallet:
                  type: string
      responses:
        '200':
          description: Sell offer created

  /user:
    get:
      summary: Get user profile details
      tags: [User]
      responses:
        '200':
          description: User info
