openapi: "3.0.0"
info:
  title: "SeagullCoin NFT Minting API"
  description: "API for minting SeagullCoin-only NFTs, verifying payments, and interacting with the SeagullCoin network."
  version: "1.0.0"
paths:
  /mint:
    post:
      summary: "Mint a SeagullCoin NFT"
      description: "Allows a user to mint an NFT with a 0.5 SeagullCoin payment."
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                nft_name:
                  type: string
                  description: "Name of the NFT"
                nft_description:
                  type: string
                  description: "Description of the NFT"
                domain:
                  type: string
                  description: "Domain of the NFT"
                properties:
                  type: string
                  description: "Additional properties of the NFT"
                nft_file:
                  type: string
                  format: binary
                  description: "File representing the NFT image or media"
      responses:
        '200':
          description: "NFT minted successfully"
          content:
            application/json:
              example:
                success: true
                nftId: "abc123"
        '400':
          description: "Minting requires 0.5 SeagullCoin payment"
        '500':
          description: "Failed to mint NFT"
