openapi: 3.0.0
info:
  title: SGLCN-X20 Minting API
  version: 1.0.0
  description: |
    Public API for minting NFTs with SeagullCoin (SGLCN-X20) only.
    - Mint NFTs by paying 0.5 SeagullCoin.
    - No XRP purchases allowed.
    - Only SeagullCoin (X20 token) allowed for offers, mints, and sales.
    - Supports CORS for marketplaces like bidds.com and xrp.cafe.

servers:
  - url: https://sglcn-x20-api.glitch.me
    description: Main API server

paths:
  /login:
    post:
      summary: Initiate XUMM login session
      operationId: loginUser
      tags:
        - Authentication
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                userToken:
                  type: string
                  description: Optional existing XUMM user token
      responses:
        '200':
          description: Login payload generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  loginPayload:
                    type: object
                  qrUrl:
                    type: string
                  websocketUrl:
                    type: string
        '500':
          description: Error initiating login

  /pay:
    post:
      summary: Initiate payment of 0.5 SeagullCoin
      operationId: initiatePayment
      tags:
        - Payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - walletAddress
              properties:
                walletAddress:
                  type: string
                  description: Wallet address initiating payment
      responses:
        '200':
          description: Payment initiated
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  paymentId:
                    type: string
        '400':
          description: Invalid request
        '500':
          description: Server error

  /mint:
    post:
      summary: Mint a new NFT after payment
      operationId: mintNFT
      tags:
        - NFT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - walletAddress
                - metadata
              properties:
                walletAddress:
                  type: string
                  description: Wallet address minting the NFT
                metadata:
                  type: object
                  description: NFT metadata (name, description, image link, etc.)
      responses:
        '200':
          description: NFT minted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  nftokenId:
                    type: string
                    description: Minted NFTokenID
        '400':
          description: Invalid mint request
        '500':
          description: Server error

  /user:
    get:
      summary: Get connected user wallet info
      operationId: getUser
      tags:
        - User
      parameters:
        - name: token
          in: query
          description: XUMM user token
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User wallet info returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  walletAddress:
                    type: string
                  balance:
                    type: number
                    format: float
        '400':
          description: Invalid token
        '500':
          description: Server error

  /nfts:
    get:
      summary: List all minted NFTs
      operationId: listNFTs
      tags:
        - NFT
      responses:
        '200':
          description: List of all NFTs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    metadata:
                      type: object
        '500':
          description: Server error

  /nft/{nftId}:
    get:
      summary: Get NFT details
      operationId: getNFT
      tags:
        - NFT
      parameters:
        - name: nftId
          in: path
          required: true
          description: NFTokenID
          schema:
            type: string
      responses:
        '200':
          description: NFT details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  metadata:
                    type: object
        '404':
          description: NFT not found
        '500':
          description: Server error

  /make-offer:
    post:
      summary: Make an offer for an NFT
      operationId: makeOffer
      tags:
        - Offer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - walletAddress
                - nftokenId
                - amount
              properties:
                walletAddress:
                  type: string
                  description: Wallet making the offer
                nftokenId:
                  type: string
                  description: NFTokenID being offered for
                amount:
                  type: number
                  format: float
                  description: Offer amount in SeagullCoin
      responses:
        '200':
          description: Offer created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  offerId:
                    type: string
        '400':
          description: Invalid offer
        '500':
          description: Server error

  /reject-offer:
    post:
      summary: Reject unauthorized XRP offers
      operationId: rejectOffer
      tags:
        - Offer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - nftokenId
                - offerId
              properties:
                nftokenId:
                  type: string
                  description: NFT to reject offer for
                offerId:
                  type: string
                  description: Offer ID to reject
      responses:
        '200':
          description: Offer rejected
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        '400':
          description: Invalid request
        '500':
          description: Server error

  /api/health:
    get:
      summary: Health check
      tags:
        - System
      responses:
        '200':
          description: API is running
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: OK
