openapi: 3.0.3
info:
  title: SGLCN-X20 Minting API
  version: 1.0.0
  description: |
    This API allows users to authenticate via XUMM, mint NFTs, purchase NFTs using SeagullCoin (SGLCN-X20), and view NFTs available for sale.
    All minting and buying operations require a successful SeagullCoin payment.
servers:
  - url: https://your-api-domain.com
    description: Production server
paths:
  /:
    get:
      summary: Welcome route
      description: Basic welcome message and API docs redirection info.
      responses:
        '200':
          description: Welcome message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /api/login:
    get:
      summary: XUMM OAuth2 Login
      description: Redirects the user to XUMM OAuth2 authentication page.
      responses:
        '302':
          description: Redirects to XUMM authentication page

  /api/logout:
    get:
      summary: XUMM Logout
      description: Clears the user's session and logs out the user.
      responses:
        '200':
          description: User logged out successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /mint:
    post:
      summary: Mint a new NFT
      description: |
        Mints a new NFT after verifying a 0.5 SeagullCoin payment.
        Requires authentication via XUMM and file upload.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - nft_name
                - nft_description
                - nft_file
              properties:
                nft_name:
                  type: string
                  description: Name of the NFT (max 100 characters)
                nft_description:
                  type: string
                  description: Description of the NFT (max 500 characters)
                domain:
                  type: string
                  description: Associated domain (optional)
                properties:
                  type: string
                  description: JSON string of additional properties
                nft_file:
                  type: string
                  format: binary
                  description: Image or video file (jpg, png, gif, mp4, webm)
      responses:
        '200':
          description: NFT minted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  mintResult:
                    type: object
        '400':
          description: Bad request (e.g., missing fields or payment not verified)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Server error during minting
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /buy-nft:
    post:
      summary: Buy an NFT
      description: |
        Purchases an NFT after verifying a SeagullCoin payment.
        Requires authentication via XUMM.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - nftId
                - price
              properties:
                nftId:
                  type: string
                  description: ID of the NFT to buy
                price:
                  type: number
                  description: Price in SeagullCoin
      responses:
        '200':
          description: NFT purchased successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  purchaseResult:
                    type: object
        '400':
          description: Bad request (missing parameters or payment failure)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Server error during purchase
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /nfts:
    get:
      summary: Get NFTs for Sale
      description: Fetches all NFTs currently listed for sale.
      responses:
        '200':
          description: NFTs fetched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  nfts:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        price:
                          type: string
                        description:
                          type: string
        '500':
          description: Error fetching NFTs
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
