openapi: 3.0.3
info:
  title: SGLCN-X20 Minting API
  version: 1.0.0
  description: |
    Public API for minting NFTs with SeagullCoin (SGLCN-X20) only.
    - Mint NFTs by paying 0.5 SeagullCoin.
    - No XRP purchases allowed.
    - Only SeagullCoin can be used for offers, sales, or mints.
    - Supports CORS for marketplaces like bidds.com and xrp.cafe.

servers:
  - url: https://outgoing-destiny-bladder.glitch.me

paths:
  /pay:
    post:
      summary: Initiate payment of 0.5 SeagullCoin to mint an NFT
      description: Creates a XUMM payload to request 0.5 SeagullCoin from user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                walletAddress:
                  type: string
                  example: "rYourWalletAddressHere"
      responses:
        '200':
          description: Payment payload created
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                  qr_url:
                    type: string
        '400':
          description: Missing or invalid parameters

  /mint:
    post:
      summary: Mint an NFT after confirming payment
      description: Mints an NFT if payment of 0.5 SeagullCoin is confirmed.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - walletAddress
                - fileUrl
                - name
                - description
              properties:
                walletAddress:
                  type: string
                  example: "rYourWalletAddressHere"
                fileUrl:
                  type: string
                  example: "ipfs://your_ipfs_cid_here"
                name:
                  type: string
                  example: "My Seagull NFT"
                description:
                  type: string
                  example: "An exclusive SeagullCoin NFT!"
                collection:
                  type: string
                  example: "Seagull Collection" 
      responses:
        '200':
          description: NFT minted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  nftoken_id:
                    type: string
        '400':
          description: Payment not found or invalid mint data

  /user:
    get:
      summary: Get NFTs owned by a wallet
      description: Returns list of NFTs owned by provided wallet address.
      parameters:
        - in: query
          name: walletAddress
          schema:
            type: string
          required: true
          description: Wallet address to fetch NFTs for
      responses:
        '200':
          description: List of NFTs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    nftoken_id:
                      type: string
                    metadata_url:
                      type: string
                    name:
                      type: string
                    description:
                      type: string
        '400':
          description: Missing walletAddress
