[[CURRENCIES]]
code = "SeagullCoin"
issuer = "rnqiA8vuNriU9pqD1ZDGFH8ajQBL25Wkno"
network = "main"
desc = "The Gold Stamdard of the Bored Seagull Club ecosystem.
SeagullCoin acts as the plumbing of our Ecosystem, with pairing to XRP, and highly liquid to Xau
SeagullCoin is the perfect long-term hedge asset with future collateral loan utility"
icon = "https://outgoing-destiny-bladder.glitch.me/seagullcoin-logo.png"
